### ISSUE TITLE
tomato plant missing - need some kind of "last seen at" dashboard perhaps?

### ISSUE THREAD

**Issue by jhpoelen** [sudomesh/gardenmesh#4]
last seen: 

1 July 2017 18:04 Saturday Counter Culture Labs, plant box (see image) 

last measurements from meshygarden.tsv -

```tsv
temp	6	28	C	1498957458298	a0:20:a6:21:61:bd
humi	6	35.7	pct	1498957458371	a0:20:a6:21:61:bd
soil	6	412	pct	1498957458400	a0:20:a6:21:61:bd
temp	7	28	C	1498957758290	a0:20:a6:21:61:bd
humi	7	35.3	pct	1498957758363	a0:20:a6:21:61:bd
soil	7	412	pct	1498957758391	a0:20:a6:21:61:bd
```

Did firmware crash? Out of power? No signal?
![tomato](https://user-images.githubusercontent.com/1084872/27771487-305eef44-5f04-11e7-9001-8656b99230f5.png)

**Comment by Mgabiati** [comment]
Grant is updating the prototype, it is still okay!
